### PR TITLE
Py3 conversion

### PR DESCRIPTION
**Pull request by x10an14**
Tested locally with Python 3.4+! =)

### CODE REVIEW

**Comment by larkly** [comment]
Awesome, C. While I only wanted something quick and dirty for this thing, your patch makes it look just beautiful. I'll give it a spin when I get home.

**Comment by x10an14** [comment]
@larkly Hahaha, awesome, thanks for the kind words =)

Also gave you PR #2 (which is based on this PR), due to your flattery^^ 
That PR remains untested though, but it should be pretty straight forward methinks.

**Comment by larkly** [comment]
@x10an14 That type-hinting commit didn't really work. From a virtualenv after pip -r requirements.txt:

```
(code) [root@3c5073631c90 source]# python3.4 ./app.py
Traceback (most recent call last):
  File "./app.py", line 34, in <module>
    def ping(host: string=None):
NameError: name 'string' is not defined
```

Now, I realize that I need to sit down and get more into python3.4+, as I wasn't sure how to fix it, so I just reverted it for now. Runs fine without it. Will test on Openshift as well before merging.

**Comment by x10an14** [comment]
derp. Shouldn't say "string", should be "str"...
My bad. Has nothing to do with Python >= 3.0

**Comment by larkly** [comment]
Got the webserver running, but the ping function doesn't work:

```
192.168.99.1 - - [30/Oct/2016 12:18:02] "GET /ping/8.8.8.8 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/code/lib/python3.4/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/code/lib/python3.4/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/code/lib/python3.4/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/code/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/code/lib/python3.4/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/code/lib/python3.4/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/code/lib/python3.4/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/code/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/code/lib/python3.4/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/code/lib/python3.4/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/code/source/app.py", line 50, in ping
    universal_newlines=True)
  File "/usr/lib64/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.4/subprocess.py", line 1345, in _execute_child
    args = list(args)
TypeError: 'NoneType' object is not iterable
```

**Comment by x10an14** [comment]
Here's the problem: 

```
In [1]: test = ["a", "b", "c"]

In [2]: args = list(test)

In [3]: args = list(test.append(None))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-30dadc423682> in <module>()
----> 1 args = list(test.append(None))

TypeError: 'NoneType' object is not iterable

In [4]:        
```

Here's the solution:

```
    # Default time_limit of hardcoded 16 seconds.
    #   (It's a 4-packet ping for crying out loud...)
    cmd, time_limit = "ping -c 4".split(" "), 16
    proc = subprocess.Popen(
        args=cmd.append(host) if host else cmd,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        universal_newlines=True)
```

=> `args=cmd.append(host) if host else cmd,`

EDIT:

More curious as to why 

```
    if not host:
        return render_template(....)

    # Default time_limit of hardcoded 16 seconds.
    #   (It's a 4-packet ping for crying out loud...)
   (....)
```

Don't catch that though. The `if not host` should've made it skip the `subprocess.Popen()`

**Comment by x10an14** [comment]
A more elaborate discussion of `if not x:` in Python: [http://stackoverflow.com/questions/100732/why-is-if-not-someobj-better-than-if-someobj-none-in-python](http://stackoverflow.com/questions/100732/why-is-if-not-someobj-better-than-if-someobj-none-in-python)

**Comment by larkly** [comment]
Well, "if not host" does in fact work, and renders the template with the boilerplate return_data. It bombs when I try an URL where host variable gets set. Adding "if host else cmd" to the subprocess args as per your suggestion didn't have any effect; it still throws the TypeError as part of the subprocess.Popen call.

**Comment by larkly** [comment]
```
>>> cmd = ['ping', '-c', '4', '8.8.8.8']
>>> proc = subprocess.Popen(args=cmd, stdout=subprocess.PIPE, stdin=subprocess.PIPE)
```

That worked fine.

```
>>> cmd = ['ping', '-c', '4']
>>> proc = subprocess.Popen(args=cmd.append('8.8.8.8'), stdout=subprocess.PIPE, stdin=subprocess.PIPE)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.4/subprocess.py", line 1345, in _execute_child
    args = list(args)
TypeError: 'NoneType' object is not iterable
```

That didn't work. For some reason, it doesn't seem like we can append to the list inside the subprocess call.

**Comment by x10an14** [comment]
Great find =)

Thumbs up! Confusing why that is though. I'll make a quick commit suggestion how to fix that pythonically in a pretty manner^^ Give me 4 mins.

**Comment by x10an14** [comment]
Added PR #3 as an apology for shitty local testing! (Both it and PR #2 have now been locally tested a bit more properly)!

**Review by larkly — APPROVED** [review]
Great success!

**Pull request merged**
